// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldCup2026.Data;

#nullable disable

namespace WorldCup2026.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606133522_AddThirdPlaceTable")]
    partial class AddThirdPlaceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldCup2026.Models.GroupPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PredictedPosition")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("GroupPredictions");
                });

            modelBuilder.Entity("WorldCup2026.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KickOffTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayTeamId = 2,
                            HomeTeamId = 1,
                            KickOffTime = new DateTime(2026, 6, 11, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 1,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            AwayTeamId = 4,
                            HomeTeamId = 3,
                            KickOffTime = new DateTime(2026, 6, 12, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 4,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 3,
                            AwayTeamId = 6,
                            HomeTeamId = 5,
                            KickOffTime = new DateTime(2026, 6, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 5,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 4,
                            AwayTeamId = 8,
                            HomeTeamId = 7,
                            KickOffTime = new DateTime(2026, 6, 13, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 11,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 5,
                            AwayTeamId = 10,
                            HomeTeamId = 9,
                            KickOffTime = new DateTime(2026, 6, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 6,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 6,
                            AwayTeamId = 12,
                            HomeTeamId = 11,
                            KickOffTime = new DateTime(2026, 6, 13, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 7,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 7,
                            AwayTeamId = 14,
                            HomeTeamId = 13,
                            KickOffTime = new DateTime(2026, 6, 14, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 12,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 8,
                            AwayTeamId = 16,
                            HomeTeamId = 15,
                            KickOffTime = new DateTime(2026, 6, 14, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 8,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 9,
                            AwayTeamId = 18,
                            HomeTeamId = 17,
                            KickOffTime = new DateTime(2026, 6, 14, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 13,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 10,
                            AwayTeamId = 20,
                            HomeTeamId = 19,
                            KickOffTime = new DateTime(2026, 6, 15, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 9,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 11,
                            AwayTeamId = 22,
                            HomeTeamId = 21,
                            KickOffTime = new DateTime(2026, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 14,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 12,
                            AwayTeamId = 24,
                            HomeTeamId = 23,
                            KickOffTime = new DateTime(2026, 6, 15, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 10,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 13,
                            AwayTeamId = 26,
                            HomeTeamId = 25,
                            KickOffTime = new DateTime(2026, 6, 16, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 15,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 14,
                            AwayTeamId = 28,
                            HomeTeamId = 27,
                            KickOffTime = new DateTime(2026, 6, 16, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 2,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 15,
                            AwayTeamId = 30,
                            HomeTeamId = 29,
                            KickOffTime = new DateTime(2026, 6, 16, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 3,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 16,
                            AwayTeamId = 32,
                            HomeTeamId = 31,
                            KickOffTime = new DateTime(2026, 6, 17, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 16,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 17,
                            AwayTeamId = 34,
                            HomeTeamId = 33,
                            KickOffTime = new DateTime(2026, 6, 17, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 1,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 18,
                            AwayTeamId = 36,
                            HomeTeamId = 35,
                            KickOffTime = new DateTime(2026, 6, 17, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 4,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 19,
                            AwayTeamId = 38,
                            HomeTeamId = 37,
                            KickOffTime = new DateTime(2026, 6, 18, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 6,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 20,
                            AwayTeamId = 40,
                            HomeTeamId = 39,
                            KickOffTime = new DateTime(2026, 6, 18, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 7,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 21,
                            AwayTeamId = 42,
                            HomeTeamId = 41,
                            KickOffTime = new DateTime(2026, 6, 18, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 8,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 22,
                            AwayTeamId = 44,
                            HomeTeamId = 43,
                            KickOffTime = new DateTime(2026, 6, 19, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 9,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 23,
                            AwayTeamId = 46,
                            HomeTeamId = 45,
                            KickOffTime = new DateTime(2026, 6, 19, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 10,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 24,
                            AwayTeamId = 48,
                            HomeTeamId = 47,
                            KickOffTime = new DateTime(2026, 6, 19, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 11,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 25,
                            AwayTeamId = 3,
                            HomeTeamId = 1,
                            KickOffTime = new DateTime(2026, 6, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 1,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 26,
                            AwayTeamId = 4,
                            HomeTeamId = 2,
                            KickOffTime = new DateTime(2026, 6, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 2,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 27,
                            AwayTeamId = 7,
                            HomeTeamId = 5,
                            KickOffTime = new DateTime(2026, 6, 20, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 4,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 28,
                            AwayTeamId = 8,
                            HomeTeamId = 6,
                            KickOffTime = new DateTime(2026, 6, 21, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 5,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 29,
                            AwayTeamId = 11,
                            HomeTeamId = 9,
                            KickOffTime = new DateTime(2026, 6, 21, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 12,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 30,
                            AwayTeamId = 12,
                            HomeTeamId = 10,
                            KickOffTime = new DateTime(2026, 6, 21, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 13,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 31,
                            AwayTeamId = 15,
                            HomeTeamId = 13,
                            KickOffTime = new DateTime(2026, 6, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 11,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 32,
                            AwayTeamId = 16,
                            HomeTeamId = 14,
                            KickOffTime = new DateTime(2026, 6, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 14,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 33,
                            AwayTeamId = 19,
                            HomeTeamId = 17,
                            KickOffTime = new DateTime(2026, 6, 22, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 15,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 34,
                            AwayTeamId = 20,
                            HomeTeamId = 18,
                            KickOffTime = new DateTime(2026, 6, 23, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 3,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 35,
                            AwayTeamId = 23,
                            HomeTeamId = 21,
                            KickOffTime = new DateTime(2026, 6, 23, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 16,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 36,
                            AwayTeamId = 24,
                            HomeTeamId = 22,
                            KickOffTime = new DateTime(2026, 6, 23, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 6,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 37,
                            AwayTeamId = 27,
                            HomeTeamId = 25,
                            KickOffTime = new DateTime(2026, 6, 24, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 7,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 38,
                            AwayTeamId = 28,
                            HomeTeamId = 26,
                            KickOffTime = new DateTime(2026, 6, 24, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 8,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 39,
                            AwayTeamId = 31,
                            HomeTeamId = 29,
                            KickOffTime = new DateTime(2026, 6, 24, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 9,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 40,
                            AwayTeamId = 32,
                            HomeTeamId = 30,
                            KickOffTime = new DateTime(2026, 6, 25, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 10,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 41,
                            AwayTeamId = 35,
                            HomeTeamId = 33,
                            KickOffTime = new DateTime(2026, 6, 25, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 1,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 42,
                            AwayTeamId = 36,
                            HomeTeamId = 34,
                            KickOffTime = new DateTime(2026, 6, 25, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 4,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 43,
                            AwayTeamId = 39,
                            HomeTeamId = 37,
                            KickOffTime = new DateTime(2026, 6, 26, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 5,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 44,
                            AwayTeamId = 40,
                            HomeTeamId = 38,
                            KickOffTime = new DateTime(2026, 6, 26, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 12,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 45,
                            AwayTeamId = 43,
                            HomeTeamId = 41,
                            KickOffTime = new DateTime(2026, 6, 26, 23, 59, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 13,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 46,
                            AwayTeamId = 44,
                            HomeTeamId = 42,
                            KickOffTime = new DateTime(2026, 6, 27, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 14,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 47,
                            AwayTeamId = 47,
                            HomeTeamId = 45,
                            KickOffTime = new DateTime(2026, 6, 27, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 11,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 48,
                            AwayTeamId = 48,
                            HomeTeamId = 46,
                            KickOffTime = new DateTime(2026, 6, 27, 23, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 15,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 49,
                            AwayTeamId = 1,
                            HomeTeamId = 4,
                            KickOffTime = new DateTime(2026, 6, 28, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 3,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 50,
                            AwayTeamId = 3,
                            HomeTeamId = 2,
                            KickOffTime = new DateTime(2026, 6, 28, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 1,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 51,
                            AwayTeamId = 5,
                            HomeTeamId = 8,
                            KickOffTime = new DateTime(2026, 6, 28, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 4,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 52,
                            AwayTeamId = 7,
                            HomeTeamId = 6,
                            KickOffTime = new DateTime(2026, 6, 28, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 5,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 53,
                            AwayTeamId = 9,
                            HomeTeamId = 12,
                            KickOffTime = new DateTime(2026, 6, 29, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 6,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 54,
                            AwayTeamId = 11,
                            HomeTeamId = 10,
                            KickOffTime = new DateTime(2026, 6, 29, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 16,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 55,
                            AwayTeamId = 13,
                            HomeTeamId = 16,
                            KickOffTime = new DateTime(2026, 6, 29, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 7,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 56,
                            AwayTeamId = 15,
                            HomeTeamId = 14,
                            KickOffTime = new DateTime(2026, 6, 29, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 8,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 57,
                            AwayTeamId = 17,
                            HomeTeamId = 20,
                            KickOffTime = new DateTime(2026, 6, 30, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 11,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 58,
                            AwayTeamId = 18,
                            HomeTeamId = 19,
                            KickOffTime = new DateTime(2026, 6, 30, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 9,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 59,
                            AwayTeamId = 21,
                            HomeTeamId = 24,
                            KickOffTime = new DateTime(2026, 6, 30, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 12,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 60,
                            AwayTeamId = 23,
                            HomeTeamId = 22,
                            KickOffTime = new DateTime(2026, 6, 30, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 13,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 61,
                            AwayTeamId = 25,
                            HomeTeamId = 28,
                            KickOffTime = new DateTime(2026, 7, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 14,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 62,
                            AwayTeamId = 27,
                            HomeTeamId = 26,
                            KickOffTime = new DateTime(2026, 7, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 10,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 63,
                            AwayTeamId = 29,
                            HomeTeamId = 32,
                            KickOffTime = new DateTime(2026, 7, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 15,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 64,
                            AwayTeamId = 30,
                            HomeTeamId = 31,
                            KickOffTime = new DateTime(2026, 7, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 2,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 65,
                            AwayTeamId = 33,
                            HomeTeamId = 36,
                            KickOffTime = new DateTime(2026, 7, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 1,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 66,
                            AwayTeamId = 35,
                            HomeTeamId = 34,
                            KickOffTime = new DateTime(2026, 7, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 4,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 67,
                            AwayTeamId = 37,
                            HomeTeamId = 40,
                            KickOffTime = new DateTime(2026, 7, 2, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 5,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 68,
                            AwayTeamId = 39,
                            HomeTeamId = 38,
                            KickOffTime = new DateTime(2026, 7, 2, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 6,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 69,
                            AwayTeamId = 41,
                            HomeTeamId = 44,
                            KickOffTime = new DateTime(2026, 7, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 11,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 70,
                            AwayTeamId = 42,
                            HomeTeamId = 43,
                            KickOffTime = new DateTime(2026, 7, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 16,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 71,
                            AwayTeamId = 45,
                            HomeTeamId = 48,
                            KickOffTime = new DateTime(2026, 7, 3, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 7,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 72,
                            AwayTeamId = 47,
                            HomeTeamId = 46,
                            KickOffTime = new DateTime(2026, 7, 3, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 8,
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("WorldCup2026.Models.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Stadiums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 87523,
                            City = "Mexico City",
                            Country = "Mexico",
                            Name = "Estadio Azteca"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 53500,
                            City = "Monterrey",
                            Country = "Mexico",
                            Name = "Estadio BBVA"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 48071,
                            City = "Guadalajara",
                            Country = "Mexico",
                            Name = "Estadio Akron"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 54500,
                            City = "Vancouver",
                            Country = "Canada",
                            Name = "BC Place"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 30000,
                            City = "Toronto",
                            Country = "Canada",
                            Name = "BMO Field"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 82500,
                            City = "East Rutherford",
                            Country = "USA",
                            Name = "MetLife Stadium"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 80000,
                            City = "Arlington",
                            Country = "USA",
                            Name = "AT&T Stadium"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 76416,
                            City = "Kansas City",
                            Country = "USA",
                            Name = "Arrowhead Stadium"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 72220,
                            City = "Houston",
                            Country = "USA",
                            Name = "NRG Stadium"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 71000,
                            City = "Atlanta",
                            Country = "USA",
                            Name = "Mercedes-Benz Stadium"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 70240,
                            City = "Inglewood",
                            Country = "USA",
                            Name = "SoFi Stadium"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 69796,
                            City = "Philadelphia",
                            Country = "USA",
                            Name = "Lincoln Financial Field"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 69000,
                            City = "Seattle",
                            Country = "USA",
                            Name = "Lumen Field"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 68500,
                            City = "Santa Clara",
                            Country = "USA",
                            Name = "Levi's Stadium"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 65878,
                            City = "Foxborough",
                            Country = "USA",
                            Name = "Gillette Stadium"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 64767,
                            City = "Miami Gardens",
                            Country = "USA",
                            Name = "Hard Rock Stadium"
                        });
                });

            modelBuilder.Entity("WorldCup2026.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupLetter")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupLetter = "A",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 2,
                            GroupLetter = "A",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 3,
                            GroupLetter = "A",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 4,
                            GroupLetter = "A",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 5,
                            GroupLetter = "B",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 6,
                            GroupLetter = "B",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 7,
                            GroupLetter = "B",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 8,
                            GroupLetter = "B",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 9,
                            GroupLetter = "C",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 10,
                            GroupLetter = "C",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 11,
                            GroupLetter = "C",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 12,
                            GroupLetter = "C",
                            Name = "Scotland"
                        },
                        new
                        {
                            Id = 13,
                            GroupLetter = "D",
                            Name = "USA"
                        },
                        new
                        {
                            Id = 14,
                            GroupLetter = "D",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 15,
                            GroupLetter = "D",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 16,
                            GroupLetter = "D",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 17,
                            GroupLetter = "E",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 18,
                            GroupLetter = "E",
                            Name = "Curacao"
                        },
                        new
                        {
                            Id = 19,
                            GroupLetter = "E",
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = 20,
                            GroupLetter = "E",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 21,
                            GroupLetter = "F",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 22,
                            GroupLetter = "F",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 23,
                            GroupLetter = "F",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 24,
                            GroupLetter = "F",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 27,
                            GroupLetter = "G",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 28,
                            GroupLetter = "G",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 31,
                            GroupLetter = "G",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 32,
                            GroupLetter = "G",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 29,
                            GroupLetter = "H",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 30,
                            GroupLetter = "H",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 25,
                            GroupLetter = "H",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 26,
                            GroupLetter = "H",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 33,
                            GroupLetter = "I",
                            Name = "France"
                        },
                        new
                        {
                            Id = 34,
                            GroupLetter = "I",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 35,
                            GroupLetter = "I",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 36,
                            GroupLetter = "I",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 37,
                            GroupLetter = "J",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 38,
                            GroupLetter = "J",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 39,
                            GroupLetter = "J",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 40,
                            GroupLetter = "J",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 41,
                            GroupLetter = "K",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 42,
                            GroupLetter = "K",
                            Name = "DR Congo"
                        },
                        new
                        {
                            Id = 43,
                            GroupLetter = "K",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 44,
                            GroupLetter = "K",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 45,
                            GroupLetter = "L",
                            Name = "England"
                        },
                        new
                        {
                            Id = 46,
                            GroupLetter = "L",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 47,
                            GroupLetter = "L",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 48,
                            GroupLetter = "L",
                            Name = "Panama"
                        });
                });

            modelBuilder.Entity("WorldCup2026.Models.ThirdPlacePrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("ThirdPlacePredictions");
                });

            modelBuilder.Entity("WorldCup2026.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@worldcup2026.com",
                            PasswordHash = "123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("WorldCup2026.Models.GroupPrediction", b =>
                {
                    b.HasOne("WorldCup2026.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WorldCup2026.Models.Match", b =>
                {
                    b.HasOne("WorldCup2026.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorldCup2026.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorldCup2026.Models.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("WorldCup2026.Models.ThirdPlacePrediction", b =>
                {
                    b.HasOne("WorldCup2026.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
