// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldCup2026.Data;

#nullable disable

namespace WorldCup2026.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606065333_AddUserTableAndAdminSeeding")]
    partial class AddUserTableAndAdminSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldCup2026.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KickOffTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("StadiumId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayTeamId = 2,
                            HomeTeamId = 1,
                            KickOffTime = new DateTime(2026, 6, 11, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 1,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            AwayTeamId = 4,
                            HomeTeamId = 3,
                            KickOffTime = new DateTime(2026, 6, 12, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 4,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 3,
                            AwayTeamId = 6,
                            HomeTeamId = 5,
                            KickOffTime = new DateTime(2026, 6, 12, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 5,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 4,
                            AwayTeamId = 8,
                            HomeTeamId = 7,
                            KickOffTime = new DateTime(2026, 6, 13, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            StadiumId = 11,
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("WorldCup2026.Models.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Stadiums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 87523,
                            City = "Mexico City",
                            Country = "Mexico",
                            Name = "Estadio Azteca"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 53500,
                            City = "Monterrey",
                            Country = "Mexico",
                            Name = "Estadio BBVA"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 48071,
                            City = "Guadalajara",
                            Country = "Mexico",
                            Name = "Estadio Akron"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 54500,
                            City = "Vancouver",
                            Country = "Canada",
                            Name = "BC Place"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 30000,
                            City = "Toronto",
                            Country = "Canada",
                            Name = "BMO Field"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 82500,
                            City = "East Rutherford",
                            Country = "USA",
                            Name = "MetLife Stadium"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 80000,
                            City = "Arlington",
                            Country = "USA",
                            Name = "AT&T Stadium"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 76416,
                            City = "Kansas City",
                            Country = "USA",
                            Name = "Arrowhead Stadium"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 72220,
                            City = "Houston",
                            Country = "USA",
                            Name = "NRG Stadium"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 71000,
                            City = "Atlanta",
                            Country = "USA",
                            Name = "Mercedes-Benz Stadium"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 70240,
                            City = "Inglewood",
                            Country = "USA",
                            Name = "SoFi Stadium"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 69796,
                            City = "Philadelphia",
                            Country = "USA",
                            Name = "Lincoln Financial Field"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 69000,
                            City = "Seattle",
                            Country = "USA",
                            Name = "Lumen Field"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 68500,
                            City = "Santa Clara",
                            Country = "USA",
                            Name = "Levi's Stadium"
                        },
                        new
                        {
                            Id = 15,
                            Capacity = 65878,
                            City = "Foxborough",
                            Country = "USA",
                            Name = "Gillette Stadium"
                        },
                        new
                        {
                            Id = 16,
                            Capacity = 64767,
                            City = "Miami Gardens",
                            Country = "USA",
                            Name = "Hard Rock Stadium"
                        });
                });

            modelBuilder.Entity("WorldCup2026.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupLetter")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupLetter = "A",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 2,
                            GroupLetter = "A",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 3,
                            GroupLetter = "A",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 4,
                            GroupLetter = "A",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 5,
                            GroupLetter = "B",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 6,
                            GroupLetter = "B",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 7,
                            GroupLetter = "B",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 8,
                            GroupLetter = "B",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 9,
                            GroupLetter = "C",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 10,
                            GroupLetter = "C",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 11,
                            GroupLetter = "C",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 12,
                            GroupLetter = "C",
                            Name = "Scotland"
                        },
                        new
                        {
                            Id = 13,
                            GroupLetter = "D",
                            Name = "USA"
                        },
                        new
                        {
                            Id = 14,
                            GroupLetter = "D",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 15,
                            GroupLetter = "D",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 16,
                            GroupLetter = "D",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 17,
                            GroupLetter = "E",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 18,
                            GroupLetter = "E",
                            Name = "Curacao"
                        },
                        new
                        {
                            Id = 19,
                            GroupLetter = "E",
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = 20,
                            GroupLetter = "E",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 21,
                            GroupLetter = "F",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 22,
                            GroupLetter = "F",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 23,
                            GroupLetter = "F",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 24,
                            GroupLetter = "F",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 25,
                            GroupLetter = "G",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 26,
                            GroupLetter = "G",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 27,
                            GroupLetter = "G",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 28,
                            GroupLetter = "G",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 29,
                            GroupLetter = "H",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 30,
                            GroupLetter = "H",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 31,
                            GroupLetter = "H",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 32,
                            GroupLetter = "H",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 33,
                            GroupLetter = "I",
                            Name = "France"
                        },
                        new
                        {
                            Id = 34,
                            GroupLetter = "I",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 35,
                            GroupLetter = "I",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 36,
                            GroupLetter = "I",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 37,
                            GroupLetter = "J",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 38,
                            GroupLetter = "J",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 39,
                            GroupLetter = "J",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 40,
                            GroupLetter = "J",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 41,
                            GroupLetter = "K",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 42,
                            GroupLetter = "K",
                            Name = "DR Congo"
                        },
                        new
                        {
                            Id = 43,
                            GroupLetter = "K",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 44,
                            GroupLetter = "K",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 45,
                            GroupLetter = "L",
                            Name = "England"
                        },
                        new
                        {
                            Id = 46,
                            GroupLetter = "L",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 47,
                            GroupLetter = "L",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 48,
                            GroupLetter = "L",
                            Name = "Panama"
                        });
                });

            modelBuilder.Entity("WorldCup2026.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@worldcup2026.com",
                            PasswordHash = "$2a$11$6pD4R7Zp4M1i8gE6fXm9UeZ8G5vK0T4vJ7yL0f6R2z4A5wS6n3B6e",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("WorldCup2026.Models.Match", b =>
                {
                    b.HasOne("WorldCup2026.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorldCup2026.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorldCup2026.Models.Stadium", "Stadium")
                        .WithMany()
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Stadium");
                });
#pragma warning restore 612, 618
        }
    }
}
